name: CreoBank CI/CD

on:
  push:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: make build

      - name: Run unit tests  
        run: make test

      - name: Run linting  
        run: make lint

      - name: Publish coverage 
        uses: actions/upload-coverage@v3
        with:
          file: /coverage/*.lcov

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: binaries
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build 
        uses: actions/download-artifact@v3
        with:
          name: binaries  

      - name: Deploy to production
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./dist/

  sdk-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Docs  
        run: make docs

      - name: Publish Docs
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
