name: CreoBank Continuous Integration And Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Unit Tests
        run: npm test

      - name: Run Integration Tests
        run: npm run test:integration

      - name: Run End-to-End Tests
        run: npm run test:e2e

      - name: Static Code Analysis
        run: npm run lint

      - name: Dependency Vulnerability Scanning
        run: npm audit

      - name: Container Security Scanning
        run: docker scan creobank/creobank-app:latest

      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: Tests/XCTest.swift

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: Tests/XCTest.swift

      - name: Deploy to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: creobank-sdk
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
          package: Backend/CreoBank.swift

      - name: Publish Docker Container
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/creobank-app:latest .
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/creobank-app:latest

      - name: Deploy Docker Container to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: creobank-rg
          dns-name-label: creobank-app
          image-name: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/creobank-app:latest

  # ... other jobs like monitor, ui-testing, environment-as-code, github-sponsorships, sdk-documentation ...
  
