name: Xcode CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15' # Specify Xcode 15
    - name: Install dependencies
      run: xcodebuild -resolvePackageDependencies
    - name: Build and Test
      run: xcodebuild -scheme CreoBank -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' build test
      
