name: Xcode Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.2.1' # Specify your Xcode version here

    - name: Xcodebuild Action
      uses: marketplace/actions/xcodebuild-action
      with:
        project-path: CreoBank.xcodeproj # Replace with your project path
        scheme: CreoBank
        sdk: iphonesimulator
        destination: 'platform=iOS Simulator,name=iPhone 13,OS=15.0'
        
