name: Xcode Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_15.app'
    - name: Install Dependencies
      run: xcodebuild -resolvePackageDependencies
    - name: Build
      run: xcodebuild -scheme 'YourScheme' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' build
    - name: Test
      run: xcodebuild -scheme 'YourScheme' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' test
      
